"""VBHNEngine — Unified Deep Seam for Consolidating Vietnamese Legal Documents."""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .ast_parser import ASTNode, ASTParser, DeltaPatch
from .patch_generator import DeltaPatchGenerator
from .vbhn_merger import VBHNMerger


@dataclass
class MergedLegalDocument:
    """Represents a consolidated legal document generated by VBHNEngine."""

    title: str
    content: str
    patch_summary: dict[str, int] = field(default_factory=dict)
    nodes: list[ASTNode] = field(default_factory=list)
    output_path: Path | None = None


class VBHNEngine:
    """Unified Deep Seam for Consolidating Vietnamese Legal Documents (VBHN).

    Encapsulates AST parsing, delta patch calculation, AST tree merging, and markdown generation.
    """

    def __init__(self) -> None:
        self.parser = ASTParser()
        self.patch_generator = DeltaPatchGenerator()
        self.merger = VBHNMerger()

    def merge_documents(
        self,
        base_doc: str | Path,
        amending_doc: str | Path | DeltaPatch,
        doc_meta: dict[str, Any] | None = None,
        output_path: Path | None = None,
    ) -> MergedLegalDocument:
        """Consolidate a base document with an amending document or DeltaPatch."""
        if isinstance(base_doc, Path) or (isinstance(base_doc, str) and Path(base_doc).is_file()):
            base_text = Path(base_doc).read_text(encoding="utf-8")
        else:
            base_text = str(base_doc)

        base_nodes = self.parser.parse_markdown(base_text)

        meta = doc_meta or {}
        mock_llm = meta.get("mock_llm_response")

        if isinstance(amending_doc, DeltaPatch):
            patch = amending_doc
        elif isinstance(amending_doc, (str, Path)) and (
            isinstance(amending_doc, Path) or Path(str(amending_doc)).is_file()
        ):
            amending_text = Path(amending_doc).read_text(encoding="utf-8")
            patch = self.patch_generator.generate_patch_from_text(
                target_doc_id="base",
                amending_doc_id="amending",
                original_text=base_text,
                amending_text=amending_text,
                mock_llm_response=mock_llm,
            )
        else:
            amending_text = str(amending_doc)
            patch = self.patch_generator.generate_patch_from_text(
                target_doc_id="base",
                amending_doc_id="amending",
                original_text=base_text,
                amending_text=amending_text,
                mock_llm_response=mock_llm,
            )

        merged_nodes = self.merger.apply_patch(base_nodes, patch)
        merged_content = self.merger.export_visual_diff_markdown(merged_nodes)

        meta = doc_meta or {}
        title = str(meta.get("title", "Văn bản hợp nhất"))

        patch_counts = {
            "replaced": sum(
                1
                for p in patch.patches
                if (p.action.value if hasattr(p.action, "value") else str(p.action)).upper()
                == "REPLACE"
            ),
            "abrogated": sum(
                1
                for p in patch.patches
                if (p.action.value if hasattr(p.action, "value") else str(p.action)).upper()
                == "ABROGATE"
            ),
            "inserted": sum(
                1
                for p in patch.patches
                if (p.action.value if hasattr(p.action, "value") else str(p.action))
                .upper()
                .startswith("INSERT")
            ),
            "suspended": sum(
                1
                for p in patch.patches
                if (p.action.value if hasattr(p.action, "value") else str(p.action)).upper()
                == "SUSPEND"
            ),
        }

        out_ref: Path | None = None
        if output_path:
            out_p = Path(output_path)
            out_p.parent.mkdir(parents=True, exist_ok=True)
            out_p.write_text(merged_content, encoding="utf-8")
            out_ref = out_p

        return MergedLegalDocument(
            title=title,
            content=merged_content,
            patch_summary=patch_counts,
            nodes=merged_nodes,
            output_path=out_ref,
        )
