# SharePoint PnP PowerShell Provisioning Script for 'Contracts'
# Generated by SharePoint IDOP Deployment Support Toolkit
# Environment: SharePoint Online

param (
    [Parameter(Mandatory = $true)]
    [string]$SiteUrl
)

# --- Helper Functions ---

function Connect-SharePoint {
    param (
        [string]$Url
    )
    Write-Host "Connecting to SharePoint Online at $Url..."
    try {
        Connect-PnPOnline -Url $Url -Interactive -ErrorAction Stop
        Write-Host "Successfully connected to $Url" -ForegroundColor Green
    } catch {
        Write-Error "Failed to connect: $_"
        exit 1
    }
}

function Ensure-SharePointList {
    param (
        [string]$Title
    )
    Write-Host "Ensuring list '$Title' exists..."
    $list = Get-PnPList -Identity $Title -ErrorAction SilentlyContinue
    if ($null -eq $list) {
        $list = New-PnPList -Title $Title -Template GenericList
        Write-Host "Created list '$Title'." -ForegroundColor Green
    } else {
        Write-Host "List '$Title' already exists." -ForegroundColor Yellow
    }
    return $list
}

function Add-SharePointField {
    param (
        [string]$ListTitle,
        [string]$DisplayName,
        [string]$InternalName,
        [string]$Type,
        [string[]]$Choices = @(),
        [string]$LookupList = $null,
        [string]$LookupField = "Title"
    )
    Write-Host "Adding field '$DisplayName' ($Type) to list '$ListTitle'..."
    
    # Check if field already exists
    $field = Get-PnPField -List $ListTitle -Identity $InternalName -ErrorAction SilentlyContinue
    if ($null -ne $field) {
        Write-Host "Field '$InternalName' already exists in '$ListTitle'." -ForegroundColor Yellow
        return
    }

    $Required = "FALSE"
    # Helper to escape XML characters
    function Escape-XmlString {
        param ([string]$string)
        if ([string]::IsNullOrEmpty($string)) { return "" }
        return $string.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;").Replace('"', "&quot;").Replace("'", "&apos;")
    }

    $EscapedDisplayName = Escape-XmlString $DisplayName
    $EscapedInternalName = Escape-XmlString $InternalName
    $EscapedLookupField = Escape-XmlString $LookupField

    switch ($Type) {
        "Text" {
            Add-PnPField -List $ListTitle -DisplayName $DisplayName -InternalName $InternalName -Type Text -AddToDefaultView
        }
        "Note" {
            Add-PnPField -List $ListTitle -DisplayName $DisplayName -InternalName $InternalName -Type Note -AddToDefaultView
        }
        "Choice" {
            $choiceXml = "<Field Type='Choice' DisplayName='$EscapedDisplayName' Name='$EscapedInternalName' StaticName='$EscapedInternalName' Required='$Required'><CHOICES>"
            foreach ($choice in $Choices) {
                $escapedChoice = Escape-XmlString $choice
                $choiceXml += "<CHOICE>$escapedChoice</CHOICE>"
            }
            $choiceXml += "</CHOICES></Field>"
            Add-PnPFieldFromXml -List $ListTitle -FieldXml $choiceXml -AddToDefaultView
        }
        "MultiChoice" {
            $choiceXml = "<Field Type='MultiChoice' DisplayName='$EscapedDisplayName' Name='$EscapedInternalName' StaticName='$EscapedInternalName' Required='$Required'><CHOICES>"
            foreach ($choice in $Choices) {
                $escapedChoice = Escape-XmlString $choice
                $choiceXml += "<CHOICE>$escapedChoice</CHOICE>"
            }
            $choiceXml += "</CHOICES></Field>"
            Add-PnPFieldFromXml -List $ListTitle -FieldXml $choiceXml -AddToDefaultView
        }
        "User" {
            Add-PnPField -List $ListTitle -DisplayName $DisplayName -InternalName $InternalName -Type User -AddToDefaultView
        }
        "Currency" {
            Add-PnPField -List $ListTitle -DisplayName $DisplayName -InternalName $InternalName -Type Currency -AddToDefaultView
        }
        "DateTime" {
            Add-PnPField -List $ListTitle -DisplayName $DisplayName -InternalName $InternalName -Type DateTime -AddToDefaultView
        }
        "Boolean" {
            Add-PnPField -List $ListTitle -DisplayName $DisplayName -InternalName $InternalName -Type Boolean -AddToDefaultView
        }
        "Lookup" {
            if ($null -ne $LookupList -and $LookupList -ne "") {
                $targetList = Get-PnPList -Identity $LookupList
                $targetListGuid = $targetList.Id
                $xml = "<Field Type='Lookup' DisplayName='$EscapedDisplayName' Name='$EscapedInternalName' StaticName='$EscapedInternalName' List='{$targetListGuid}' ShowField='$EscapedLookupField' Required='$Required' />"
                Add-PnPFieldFromXml -List $ListTitle -FieldXml $xml -AddToDefaultView
            } else {
                Write-Error "Lookup field '$DisplayName' is missing lookup list reference."
                throw "LookupList missing"
            }
        }
        Default {
            Write-Error "Unsupported field type '$Type' for field '$DisplayName'."
            throw "Unsupported field type '$Type'"
        }
    }
    Write-Host "Successfully added field '$DisplayName'." -ForegroundColor Green
}

# --- Execution ---

# 1. Connect to Site
Connect-SharePoint -Url $SiteUrl

# 2. Ensure list exists
Ensure-SharePointList -Title "Contracts"

Add-SharePointField -ListTitle "Contracts" -DisplayName "CRM Lead" -InternalName "CRMReference" -Type "Lookup" -LookupList "CRM" -LookupField "Title"
Add-SharePointField -ListTitle "Contracts" -DisplayName "Contract Type" -InternalName "ContractType" -Type "Choice" -Choices @("NDA", "Service Agreement", "Procurement", "Employment")
Add-SharePointField -ListTitle "Contracts" -DisplayName "Contract Value" -InternalName "Value" -Type "Currency"
Add-SharePointField -ListTitle "Contracts" -DisplayName "Start Date" -InternalName "StartDate" -Type "DateTime"
Add-SharePointField -ListTitle "Contracts" -DisplayName "End Date" -InternalName "EndDate" -Type "DateTime"
Add-SharePointField -ListTitle "Contracts" -DisplayName "Signee" -InternalName "Signee" -Type "User"
Add-SharePointField -ListTitle "Contracts" -DisplayName "Contract Status" -InternalName "Status" -Type "Choice" -Choices @("Draft", "Under Review", "Active", "Expired", "Terminated")

Write-Host "Provisioning of list 'Contracts' completed successfully!" -ForegroundColor Green